spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wine_diary?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  jackson:
    time-zone: Asia/Seoul

server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  secret: wine-diary-jwt-secret-key-2024
  expiration: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.winediary: DEBUG